language: ruby

services:
  - mysql
  - postgresql

rvm:
  - 1.9.3
  - 2.0.0

gemfile:
  - $REDMINE_PATH/Gemfile

env:
  - REDMINE_VER=2.1.6 DB=mysql
  - REDMINE_VER=2.2.4 DB=mysql
  - REDMINE_VER=2.3.3 DB=mysql
  - REDMINE_VER=2.4.1 DB=mysql
  - REDMINE_VER=2.1.6 DB=postgresql
  - REDMINE_VER=2.2.4 DB=postgresql
  - REDMINE_VER=2.3.3 DB=postgresql
  - REDMINE_VER=2.4.1 DB=postgresql

matrix:
  exclude:
    - rvm: 2.0.0
      env: REDMINE_VER=2.1.6 DB=mysql
      gemfile: $REDMINE_PATH/Gemfile
    - rvm: 2.0.0
      env: REDMINE_VER=2.2.4 DB=mysql
      gemfile: $REDMINE_PATH/Gemfile
    - rvm: 2.0.0
      env: REDMINE_VER=2.1.6 DB=postgresql
      gemfile: $REDMINE_PATH/Gemfile
    - rvm: 2.0.0
      env: REDMINE_VER=2.2.4 DB=postgresql
      gemfile: $REDMINE_PATH/Gemfile

before_install:
  - export PLUGIN_NAME=redmine_tagging
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rails generate acts_as_taggable_on:migration
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME

